ALTER TABLE coffeshop.users MODIFY FULLNAME VARCHAR(50) NULL;
ALTER TABLE coffeshop.users MODIFY ADDRESS VARCHAR(50) NULL;
ALTER TABLE coffeshop.users MODIFY PHONE VARCHAR(50) NULL;
ALTER TABLE coffeshop.users MODIFY EMAIL VARCHAR(50) NULL;
ALTER TABLE coffeshop.users MODIFY DATEOFBIRTH DATE NULL;
ALTER TABLE CARTDETAILS
ADD UNIQUE KEY unique_cart_product (CARTID, PRODUCTID);
